server.port: 8762

eureka:
  client:
    serviceUrl.defaultZone: 'http://localhost:8761/eureka/'
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true

spring:
  application.name: 'gateway-service'
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/shop-realm
        registration:
          keycloak:
            client-id: shop-client
            client-secret: 2185762e-6c91-4d11-a240-8ac4fcd598dd
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid, profile
  zipkin.base-url: 'http://localhost:9411'
  boot.admin.client.url: 'http://localhost:5050'
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/, /

com.rb.alwaysontheroad.gateway:
  http-client:
    max-connections: 500
    max-idle-time: 20_000
    max-life-time: 60_000
    pending-acquire-timeout: 60_000
    evict-in-background: 120_000

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    logfile:
      external-file: ./logs/service.log
      enabled: true
    health.show-details: always
    loggers.enabled: true
